### ISSUE TITLE
ICPSR mismatch with voteview.com

### ISSUE THREAD

**Issue by rionbr** [unitedstates/congress-legislators#366]
Here are a few ICPSR numbers that do not match with voteview.com. Hopefully this helps someone along the way.
Most of the time, legislators that changed party along the way have slightly different numbers.

- Michael P. Forbes (bioguide: F000257)
-- ICPSR here: `NULL`
-- ICPSR voteview: `29542`

- Linda Smith (bioguide: S000587)
-- ICPSR here: `NULL`
-- ICPSR voteview: `29579`

- William J. Tauzin (bioguide: T000058)
-- ICPSR here: `14679 `
-- ICPSR voteview: `14679` & `94679` (changed party)

- Nathan Deal (bioguide: D000168)
-- ICPSR here: `99342`
-- ICPSR voteview: `99342` & `29342` (changed party)

- James Hayes (bioguide: H000390)
-- ICPSR here: `15418`
-- ICPSR voteview: `15418` & `95418`  (changed party)

- Gregory H. Laughlin (bioguide: L000119)
-- ICPSR here: `15611 `
-- ICPSR voteview: `15611` & `95611`  (changed party)

- Michael Parker (bioguide: P000066)
-- ICPSR here: `15617`
-- ICPSR voteview: `15617` & `95617`  (changed party)

- Wes Watkins (bioguide: W000194)
-- ICPSR here: `14462`
-- ICPSR voteview: `29749`

- Virgil H. Goode (bioguide: G000280)
-- ICPSR here: `89767`
-- ICPSR voteview: `29767`

- Matthew G. Martínez (bioguide: M000206)
-- ICPSR here: `14879`
-- ICPSR voteview: `94879`

- Rodney M. Alexander (bioguide: A000361)
-- ICPSR here: `90327`
-- ICPSR voteview: `20327`

Ralph M. Hall (bioguide: H000067)
-- ICPSR here: `14828`
-- ICPSR voteview: `14828` & `94828`  (changed party)

Parker Griffith (bioguide: G000557)
-- ICPSR here: `NULL`
-- ICPSR voteview: `20901` & `90901`  (changed party)

Vance McAllister (bioguide: M001192)
-- ICPSR here: `NULL`
-- ICPSR voteview: `21374`

Katherine M. Clark (bioguide: C001101)
-- ICPSR here: `NULL`
-- ICPSR voteview: `21375`

Bradley Byrne (bioguide: B001289)
-- ICPSR here: `NULL`
-- ICPSR voteview: `21376`

Thanks for the great work done here! =]

**Comment by JoshData** [comment]
Could you make these corrections in a pull request? (We'd need to figure out what to do with the ones that have two IDs.)

**Comment by bycoffe** [comment]
I think to faithfully include ICPSR IDs in the current format of the `legislators-*.yaml` files, they would have to be listed with each term and, when applicable, each party affiliation within a term, since members get a new ID if they switch parties or chambers mid-term. So Jim Jeffords, for example, would look like:

```
  - type: sen
    start: '1995-01-04'
    end: '2001-01-03'
    state: VT
    class: 1
    party: Republican
    icpsr: 14240
  - type: sen
    start: '2001-01-03'
    end: '2007-01-03'
    state: VT
    class: 1
    party: Independent
    url: http://jeffords.senate.gov/
    party_affiliations:
    - start: '2001-01-03'
      end: '2001-06-06'
      party: Republican
      icpsr: 14240
    - start: '2001-06-06'
      end: '2007-01-03'
      party: Independent
      icpsr: 94240
```

That seems less than ideal, since it would require a lot of redundancy and add some complication to finding the ID (check the term first, and if multiple parties are listed within the term, check each party).

Another option would be to include them as a list as part of the `id` array, with dates for when each ID was used, though that doesn't seem like a great solution.

But right now, someone trying to match the legislator files with other data using ICPSR IDs is going to run into issues.

As a side note, the new Voteview data does include members' full name as it appears in the Bioguide (e.g. JEFFORDS, James Merrill), so it is possible to go bioguide ID->name->ICPSR. If we drop the ICPSR IDs, we could then make matching to that data easier by also including the full Bioguide name, though that wouldn't help with any data set other than Voteview, without using Voteview in between.
