### ISSUE TITLE
Some birthdays are inconsistent in `legislators-historical.yaml`

### ISSUE THREAD

**Issue by muxspace** [unitedstates/congress-legislators#490]
I noticed that the birthdays for the following legislators are after their start dates in congress. This is in the `legislators-historical.yaml`. Not sure if it's a parse issue or source data issue.

```
         first      last   birthday      start        end
1432   William   Mayrant 1816-10-21 1815-12-04 1817-03-03
1935  Jeremiah    Cosden 1821-03-04 1821-12-03 1823-03-03
2618      Espy Van Horne 1825-03-04 1825-12-05 1827-03-03
2619      Espy Van Horne 1825-03-04 1827-12-03 1829-03-03
8074    Willis    Machen 1810-04-10 1797-05-15 1799-03-03
10838   Wilbur   Sanders 1834-05-02 1823-12-01 1825-03-03
11098   Edward     White 1845-11-03 1813-05-24 1815-03-03
17169  William  McMaster 1877-05-10 1817-12-01 1819-03-03
20272  William  Smathers 1891-01-07 1805-12-02 1807-03-03
20273  William  Smathers 1891-01-07 1807-10-26 1809-03-03
20274  William  Smathers 1891-01-07 1809-05-22 1811-03-03
21592    James   Huffman 1894-09-13 1809-05-22 1811-03-03
21593    James   Huffman 1894-09-13 1811-11-04 1813-03-03
21594    James   Huffman 1894-09-13 1813-05-24 1815-03-03
```

**Comment by JoshData** [comment]
I just looked at one ([Huffman](http://bioguide.congress.gov/scripts/biodisplay.pl?index=H000913)) and it appears that the birthday is correct but the terms aren't - there are term records that are completely bogus (wrong century, wrong type, wrong state - they seem to be duplicates of terms for [this other person](http://bioguide.congress.gov/scripts/biodisplay.pl?index=H000914)). `git blame` shows that it goes back to the first commit in this repo when I imported GovTrack's scrape of bioguide. Either biogiude had bad data or the scrape got it wrong.

There could be a bigger problem here than just the terms identified in your table.

**Comment by muxspace** [comment]
I see what you mean. For Huffman, the Senate data looks correct but not the HoR. 

```
  terms:
  - type: rep
    start: '1809-05-22'
    end: '1811-03-03'
    state: NJ
    district: -1
    party: Federalist
  - type: rep
    start: '1811-11-04'
    end: '1813-03-03'
    state: NJ
    district: -1
    party: Federalist
  - type: rep
    start: '1813-05-24'
    end: '1815-03-03'
    state: NJ
    district: -1
    party: Federalist
  - type: sen
    start: '1945-01-03'
    end: '1947-01-03'
    state: OH
    class: 1
    party: Democrat
```

Another one, [William Mayrant](http://bioguide.congress.gov/scripts/biodisplay.pl?index=M000288), appears to use the resignation date as the birthday: October 21, 1816. The page says "served until his resignation on October 21, 1816". Does the scraper parse the literal text on the page?
