### ISSUE TITLE
LIS IDs for committees

### ISSUE THREAD

**Issue by schmod** [unitedstates/congress-legislators#62]
Given that the information is now readily available, could we discuss the prospect of referring to committees via their LIS IDs instead of the current hodgepodge of Thomas IDs and partial LIS IDs?

At least on the Senate side, LIS IDs seem to be the de-facto standard for referring to committees, and this repository's way of providing committees (and especially subcommittees) with unique IDs seems unnecessarily convoluted.

Right now, standard committees look like

```
name: Senate Committee on Appropriations
  url: http://appropriations.senate.gov/
  thomas_id: SSAP
  senate_committee_id: SSAP
  subcommittees:
  - name: Commerce, Justice, Science, and Related Agencies
    thomas_id: '16'
  - name: Energy and Water Development
    thomas_id: '22'
-----
- type: house
  name: House Committee on Agriculture
  url: http://agriculture.house.gov/
  thomas_id: HSAG
  house_committee_id: AG
  subcommittees:
  - name: Conservation, Energy, and Forestry
    thomas_id: '15'
    address: 1301 LHOB; Washington, DC 20515
    phone: (202) 225-2171
```

In our list (as far as I can tell) the `thomas_id` always matches the `senate_committee_id`, which (I think) is supposed to be the LIS ID's prefix.  (However, LIS always refers full committees as XXXX00).  On the house side, `house_committee_id` always seems to match the second two letters of the `thomas_id`, which again, is the prefix of the LIS ID.

Similarly, for subcommittees, the `thomas_id` always seems to be equal to the LIS ID's numeric suffix.  (In the above examples, Energy & Water's LIS ID is SSAP22, while Conservation, Energy, and Forestry is HSAG15).

I'm not sure if there are any inconsistencies in here (thus justifying the duplicative specification of IDs), but it sure would seem easiest to just specify each committee and subcommittee by its LIS ID.

Thoughts?
