### ISSUE TITLE
YouTube IDs

### ISSUE THREAD

**Issue by schmod** [unitedstates/congress-legislators#80]
Mirroring #76, there are a number of places where YouTube Channel IDs are preferred over the channel's nickname.  Namely, the current iteration of the YouTube API [does not support nicknames at all](https://developers.google.com/youtube/v3/guides/working_with_channel_ids#v3).

We've already encountered this issue for the handful of legislators who have YouTube channels with no nickname.  Currently, we deal with these by using a somewhat awkward syntax, eg: `youtube: channel/UCd00b7TpKDZIr-Ujhaktvjg`

This syntax is great if you're only looking to construct a URL to the legislator's YouTube page (which follow the form of http://youtube.com/[nickname] or http://youtube.com/channel/[id]), but is awkward and inconsistent if you're doing anything else.

To allow developers to easily query YouTube's APIs from this dataset, I propose adding a `youtube_id` field, analogous to the `facebook_id` field.  Existing nicknames would stay in place (for constructing human-friendly URLs), and accounts without nicknames would _only_ have a `youtube_id` field (or we could just keep the current `youtube: /channel/[id]` scheme in place to keep things consistent -- it would be redundant, but wouldn't really hurt anything).

Two examples of how this could look:

```
- id:
    bioguide: D000617
    thomas: '02096'
    govtrack: 412505
  social:
    twitter: RepDelBene
    facebook: RepDelBene
    youtube_id: UCd00b7TpKDZIr-Ujhaktvjg
    facebook_id: '483962224987343'
```

```
- id:
    bioguide: K000383
    govtrack: 412545
  social:
    twitter: SenAngusKing
    facebook: SenatorAngusSKingJr
    youtube: SenatorAngusKing
    youtube_id: UCpp6lGvrmt0XU_lnD4Ak0gA
    facebook_id: '142803045874943'
```

Thoughts?
