### ISSUE TITLE
When subcommittees change their names, how is that captured?

### ISSUE THREAD

**Issue by barapa** [unitedstates/congress-legislators#983]
For example, it looks like the names of the House Energy & Commerce subcommittees don't match what is currently on their website.

From `committees-current.yaml`:
```
- type: house
  name: House Committee on Energy and Commerce
  url: https://energycommerce.house.gov/
  subcommittees:
  - name: Innovation, Data, and Commerce
  - name: Communications and Technology
  - name: Energy, Climate, and Grid Security
  - name: Health
  - name: Oversight and Investigations
  - name: Environment, Manufacturing, and Critical Materials
```

From the website:

![Image](https://github.com/user-attachments/assets/3cd39ef8-c209-490e-9557-b8ffde6a047d)
